---
- name: install openvpn
  apt:
    name: openvpn
    state: present
    force: yes

- name: copy certificates to clients from {{ inventory_hostname }}
  copy:
    src: "{{ inventory_hostname }}.ovpn"
    dest: "/etc/openvpn/client.conf"

- name: remove local certificate files
  become_user: "{{ lookup('env', 'USER')}}"
  file: path="./{{ inventory_hostname }}.ovpn" state=absent
  delegate_to: 127.0.0.1

# - name: edit address in certificates
#   shell:
#     cmd: |
#       HOST_IP="{{ hostvars['control'].private_ip }}"
#       sed -Ein "s/remote[ ]*([0-9\.]+)[ ]*([0-9]+)/remote $HOST_IP \2/" /etc/openvpn/client.conf

- name: ignore redirect-gateway in certificates
  shell:
    cmd: sed -Ein "/verb 3/a pull-filter ignore redirect-gateway" /etc/openvpn/client.conf

- name: reload openvpn clients
  systemd:
    name: openvpn@client
    state: restarted
    daemon_reload: true