version: 3

tasks:
  default:
    - task --list-all

  eucore:
    cmds:
      - |
        HOST="$(awk 'NR==2 {print $2}' ./ansible/hosts.ini | cut -d'=' -f2)"
        echo $HOST
        ssh -i ow-gcp-key depalma_gsp@${HOST}

  uscore:
    cmds:
      - |
        HOST="$(awk 'NR==3 {print $2}' ./ansible/hosts.ini | cut -d'=' -f2)"
        echo $HOST
        ssh -i ow-gcp-key depalma_gsp@${HOST}

  euworker:
    cmds:
      - |
        HOST="$(awk 'NR==6 {print $2}' ./ansible/hosts.ini | cut -d'=' -f2)"
        echo $HOST
        ssh -i ow-gcp-key depalma_gsp@${HOST}

  usworker:
    cmds:
      - |
        HOST="$(awk 'NR==7 {print $2}' ./ansible/hosts.ini | cut -d'=' -f2)"
        echo $HOST
        ssh -i ow-gcp-key depalma_gsp@${HOST}

  setup:
    - task: create
    - sleep 30
    - task: ansible

  create:
    cmds:
      - |
        cd opentofu
        tofu apply -auto-approve

  destroy:
    cmds:
      - |
        cd opentofu
        tofu destroy -auto-approve

  ansible:
    cmds:
      - |
        cd ansible
        ansible-playbook site.yaml

  create-functions:
    cmds:
      - |
        cd mqtt_benchs/functions
        wsk -i action update mqtt mqtt.zip --kind nodejs:12 --web true -a tag MQTT
        wsk -i action update feature_extraction feature_extraction.js --web true -a tag DB
        wsk -i action update feature_analysis feature_analysis.js --web true -a tag Cloud
        wsk -i action update refresh hello.js
