---
- name: get dependencies
  ansible.builtin.shell: mix deps.get
  args:
    chdir: "{{ ansible_env.HOME }}/funless/worker"
  environment:
    PATH: "{{ ansible_env.HOME }}/.elixir-install/installs/elixir/1.18.3-otp-27/bin:{{ ansible_env.HOME }}/.elixir-install/installs/otp/27.1.2/bin:{{ ansible_env.PATH }}"

- name: compile workers
  ansible.builtin.shell: mix compile
  args:
    chdir: "{{ ansible_env.HOME }}/funless/worker"
  environment:
    PATH: "{{ ansible_env.HOME }}/.elixir-install/installs/elixir/1.18.3-otp-27/bin:{{ ansible_env.HOME }}/.elixir-install/installs/otp/27.1.2/bin:{{ ansible_env.PATH }}"
    MIX_ENV: "prod"

- name: Create startup script for worker
  copy:
    dest: "{{ ansible_env.HOME }}/funless/worker/start_worker.sh"
    content: |
      #!/bin/bash
      export MIX_ENV=prod
      iex --name {% if inventory_hostname == 'eu_worker' %}euworker@{% else %}usworker@{% endif %}{{ ansible_default_ipv4.address }} --cookie mycookie -S mix
    mode: "0755"
