---
- name: Apply labels for openwhisk control plane
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: k8s-control-plane
        labels:
          zone: "belgium"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: worker1
        labels:
          openwhisk-role: "invoker"
          zone: "belgium"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: worker2
        labels:
          openwhisk-role: "invoker"
          zone: "belgium"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: worker3
        labels:
          openwhisk-role: "invoker"
          zone: "oregon"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: worker4
        labels:
          openwhisk-role: "invoker"
          zone: "toronto"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: controller1
        labels:
          openwhisk-role: "core"
          zone: "belgium"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: controller2
        labels:
          openwhisk-role: "core"
          zone: "oregon"

- name: Apply labels for openwhisk nodes
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: controller3
        labels:
          openwhisk-role: "core"
          zone: "toronto"
