---

- name: Label nodes
  include_tasks: labels.yml

- name: Clone openwhisk-deploy-kube
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/mattrent/openwhisk-deploy-kube.git
    dest: ~/openwhisk-deploy-kube

- name: Copy mycluster.yaml into openwhisk-deploy-kube
  become_user: "{{ ansible_user }}"
  copy:
    src: ../../../mycluster.yaml
    dest: ~/openwhisk-deploy-kube/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install Openwhisk with helm
  become_user: "{{ ansible_user }}"
  kubernetes.core.helm:
    name: owdev
    chart_ref: ~/openwhisk-deploy-kube/helm/openwhisk
    release_namespace: openwhisk
    create_namespace: yes
    values_files:
      - "/home/{{ ansible_user }}/openwhisk-deploy-kube/mycluster.yaml"
