---

- name: Label nodes
  include_tasks: labels.yml

- name: Clone openwhisk-deploy-kube
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/mattrent/openwhisk-deploy-kube.git
    dest: ~/openwhisk-deploy-kube

