---

- name: Install nfs-server
  apt:
    name: nfs-kernel-server
    state: present

- name: Creating mountable shared folders
  file: 
    path: /var/nfs/kubedata
    owner: nobody
    state: directory

- name: Configure nfs server
  copy:
    dest: /etc/exports
    content: |
      /var/nfs/kubedata *(rw,no_root_squash)
      
- name: Starting nfs server
  service:
    name: nfs-server 
    state: started
    enabled: yes

- name: Add nfs provisioner helm chart repo
  become_user: "{{ ansible_user }}"
  ansible.builtin.shell:
    cmd: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner

- name: Deploy nfs provisioner with helm
  become_user: "{{ ansible_user }}"
  kubernetes.core.helm:
    name: nfs-provisioner
    chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    release_namespace: default
    values:
      nfs:
        server: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        path: /var/nfs/kubedata

- name: Add default storage class for NFS provisioner
  become_user: "{{ ansible_user }}"
  k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1 
      kind: StorageClass 
      metadata: 
	      name: openwhisk-nfs 
	      annotations: 
		      storageclass.kubernetes.io/is-default-class: "true" 
	      provisioner: cluster.local/nfs-subdir-external-provisioner 
	      allowVolumeExpansion: true 
	      parameters: 
		      archiveOnDelete: "false"
