- name: Set peer IP for replication
  set_fact:
    peer_ip: >-
      {{ hostvars['us_controller'].ansible_default_ipv4.address
         if inventory_hostname == 'eu_controller'
         else hostvars['eu_controller'].ansible_default_ipv4.address }}

- name: Create publication for funless database
  become: true
  become_user: postgres
  postgresql_query:
    db: funless
    query: CREATE PUBLICATION funless_pub FOR ALL TABLES;

- name: Create publication for subjects database
  become: true
  become_user: postgres
  postgresql_query:
    db: subjects
    query: CREATE PUBLICATION subjects_pub FOR ALL TABLES;
- name: Create replication slot for funless database on source
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d funless -c "SELECT pg_create_logical_replication_slot('funless_slot', 'pgoutput');"

- name: Create replication slot for subjects database on source
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d subjects -c "SELECT pg_create_logical_replication_slot('subjects_slot', 'pgoutput');"

- name: Create subscription for funless database with explicit slot
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d funless -c "CREATE SUBSCRIPTION funless_sub 
      CONNECTION 'host={{ peer_ip }} port=5432 dbname=funless user=funless password=postgres' 
      PUBLICATION funless_pub 
      WITH (create_slot = false, slot_name = 'funless_slot');"

- name: Create subscription for subjects database with explicit slot
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d subjects -c "CREATE SUBSCRIPTION subjects_sub 
      CONNECTION 'host={{ peer_ip }} port=5432 dbname=subjects user=funless password=postgres' 
      PUBLICATION subjects_pub 
      WITH (create_slot = false, slot_name = 'subjects_slot');"

# - name: Run mix ecto.seed (only on EU node)
#   shell: "mix ecto.seed"
#   args:
#     chdir: "{{ ansible_env.HOME }}/funless/core"
#   environment:
#     PATH: "{{ ansible_env.HOME }}/.elixir-install/installs/elixir/1.18.3-otp-27/bin:{{ ansible_env.HOME }}/.elixir-install/installs/otp/27.1.2/bin:{{ ansible_env.PATH }}"
#     MIX_ENV: "prod"
#     SECRET_KEY_BASE: "secret_key"
#     PGUSER: funless
#     PGPASSWORD: funless_password
#     PGHOST: "{{ ansible_default_ipv4.address }}"
#   when: inventory_hostname == 'eu_controller'
