- name: Move mqtt folder to host
  ansible.builtin.copy:
    src: "{{ lookup('env', 'PWD') }}/mqtt/mqtt_python"
    dest: ~/
    remote_src: false

- name: Install python-pip3
  apt:
    name: python3-pip
    state: present

- name: Install amqtt with pip3
  pip:
    name: amqtt
    executable: pip3
    state: present

- name: Add mongodb key
  shell: wget -qO- https://pgp.mongodb.com/server-7.0.asc | gpg --dearmor | sudo tee /usr/share/keyrings/mongodb-server-7.0.gpg >/dev/null

- name: Add mongodb repository
  shell: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/7.0 multiverse" | sudo tee -a /etc/apt/sources.list.d/mongodb-org-7.0.list

- name: Install mongodb with apt update
  apt:
    update_cache: yes
    name: mongodb-org
    state: present

- name: Start mongodb service
  service:
    name: mongod
    state: started
    enabled: yes
