---
prometheus_version: "2.53.3"
prometheus_dir: "/etc/prometheus"
prometheus_bin_dir: "/usr/local/bin"
prometheus_data_dir: "/var/lib/prometheus"
prometheus_user: "prometheus"
prometheus_group: "prometheus"
prometheus_config: "{{ prometheus_dir }}/prometheus.yml"
