---
- name: Set Prometheus version
  set_fact:
    prometheus_version: "2.53.3"

- name: Create prometheus system user
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    system: yes

- name: Create directories for Prometheus configuration and data
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus archive
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    mode: "0644"

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
    creates: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Symlink Prometheus binary
  ansible.builtin.file:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    state: link
    force: yes

- name: Symlink Promtool binary
  ansible.builtin.file:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
    dest: /usr/local/bin/promtool
    state: link
    force: yes

- name: Deploy Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Copy Prometheus consoles directory
  ansible.builtin.copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/consoles"
    dest: /etc/prometheus/consoles
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Copy Prometheus console libraries directory
  ansible.builtin.copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/console_libraries"
    dest: /etc/prometheus/console_libraries
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Create systemd service file for Prometheus
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: "0644"
  notify:
    - Reload systemd

- name: Start and enable Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
