- default:
    - workers:
        - set:
- DB:
    - workers:
        - wrk: "edgeworker"
          invalidate:
            - capacity_used: 50
        - wrk: "worker"
      strategy: best-first
- Cloud:
    - controller: "controller"
      workers:
        - set: "belgium"
      topology_tolerance: "none"
      strategy: random
  followup: fail
- MQTT:
    - controller: "edgecontroller"
      workers:
        - set: "edge"
      strategy: random
      topology_tolerance: "none"
  followup: fail
