---
# - name: update kubelet advertised address
#   shell: |
#     NODEIP=$(ip -f inet addr show tun0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
#     sed -Ein "s/Environment=\"KUBELET_CONFIG_ARGS=[^\"]*/& --node-ip=$NODEIP/" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: join cluster
  shell: "{{ hostvars['control'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
