---
- name: Gather IP addresses for Prometheus scrape configuration
  ansible.builtin.set_fact:
    prometheus_targets:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "funless"
        static_configs:
          - targets: "{{
              (groups.get('cores', [])
              | map('extract', hostvars, 'ansible_host')
              | map('regex_replace', '^(.*?)(?::[0-9]+)?$', '\\1:4000')
              | list)
              +
              (groups.get('workers', [])
              | map('extract', hostvars, 'ansible_host')
              | map('regex_replace', '^(.*?)(?::[0-9]+)?$', '\\1:4021')
              | list)
              }}"

- name: Create necessary directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ prometheus_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download and extract Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move Prometheus binary
  ansible.builtin.shell: "mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus {{ prometheus_bin_dir }}/"
  args:
    creates: "{{ prometheus_bin_dir }}/prometheus"

- name: Set permissions on Prometheus binary
  ansible.builtin.file:
    path: "{{ prometheus_bin_dir }}/prometheus"
    mode: "0755"

- name: Generate Prometheus configuration file
  ansible.builtin.copy:
    dest: "{{ prometheus_config }}"
    content: |
      global:
        scrape_interval: 5s
        evaluation_interval: 5s
        external_labels:
          monitor: "funless"
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: "funless"
          static_configs:
            - targets: {{ prometheus_targets[1].static_configs[0].targets | to_json }}
    mode: "0644"
  notify: Restart Prometheus

- name: Create systemd service file for Prometheus
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart={{ prometheus_bin_dir }}/prometheus --config.file={{ prometheus_config }} --storage.tsdb.path={{ prometheus_data_dir }} --web.listen-address=0.0.0.0:9090

      [Install]
      WantedBy=multi-user.target
  notify: Restart Prometheus

- name: Reload systemd and enable Prometheus service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
    state: started
