---
- hosts: kube-cluster
  gather_facts: yes
  become: yes
  roles:
    - docker

- hosts: control_plane
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/control, tags: control }

- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/worker, tags: worker }

- hosts: control_plane
  gather_facts: yes
  become: yes
  roles:
    - nfs
- hosts: control_plane
  gather_facts: yes
  become: yes
  roles:
    - openwhisk

# - hosts: mongodb
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: mongodb/install }
# - hosts: worker1
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: couchbase/worker1 }

# - hosts: worker2
#   gather_facts: yes
#   become: yes
#   roles:
#     - { role: couchbase/worker2 }
